[project]
name = "sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "httpx>=0.28.1",
    "pandas>=3.0.2",
    "pillow>=12.2.0",
    "pymysql>=1.1.2",
    "streamlit>=1.56.0",
    "watchdog>=6.0.0",
]

[dependency-groups]
dev = ["ruff>=0.15.9"]

[tool.ruff]
line-length = 120
